# Generated by Django 4.1.4 on 2022-12-22 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Resolvido', 'RESOLVIDO'), ('Resolvendo', 'RESOLVENDO'), ('Não resolvido', 'NÃO RESOLVIDO')], default='Não resolvido', max_length=13)),
                ('user', models.CharField(choices=[('Luara', 'LUARA'), ('Guilherme', 'GUILHERME')], default='Luara', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ChatReclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isEnvio', models.BooleanField()),
                ('user', models.CharField(choices=[('Luara', 'LUARA'), ('Guilherme', 'GUILHERME')], default='Luara', max_length=9)),
                ('reclamacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.reclamacao')),
            ],
        ),
    ]
