# Generated by Django 4.1.4 on 2022-12-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacao',
            name='state',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='Não resolvido', max_length=13),
        ),
    ]
