# Generated by Django 4.1.4 on 2023-05-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('chat', '0004_rename_desc_chatreclamacao_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatreclamacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
