# Generated by Django 4.1.4 on 2023-05-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('user',)},
        ),
    ]
