# Generated by Django 3.2.19 on 2023-05-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default='filme', max_length=255)),
                ('name', models.CharField(default='filme', max_length=255)),
                ('desc', models.CharField(default='filme', max_length=255)),
                ('type', models.CharField(choices=[('filme', 'filme'), ('lugar', 'lugar'), ('mural', 'mural'), ('jogo', 'jogo')], default='filme', max_length=13)),
            ],
        ),
    ]
