# Generated by Django 3.2.19 on 2023-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='rating',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('filme', 'filme'), ('lugar', 'lugar'), ('mural', 'mural')], default='filme', max_length=13),
        ),
    ]
