# Generated by Django 4.1.4 on 2023-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Filme', 'filme'), ('Lugar', 'lugar'), ('Mural', 'mural'), ('Jogo', 'jogo')], default='filme', max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='Lugar',
        ),
        migrations.DeleteModel(
            name='Mural',
        ),
    ]
