# Generated by Django 3.2.19 on 2023-05-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_feature_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='photo',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
