# Generated by Django 3.2.19 on 2023-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_alter_feature_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='photo',
        ),
        migrations.AddField(
            model_name='feature',
            name='photo_file',
            field=models.FileField(default='', null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='feature',
            name='photo_url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('filme', 'filme'), ('lugar', 'lugar'), ('mural', 'mural')], default='', max_length=13),
        ),
    ]
