# Generated by Django 3.2.19 on 2023-08-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20230729_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.CharField(default='', max_length=455),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=455),
        ),
    ]
